### ISSUE TITLE
High load issue

### ISSUE THREAD

**Issue by mejsin** [feulf/raintpl3#190]
Hi 
When we have high load on our servers we see some issues with raintpl, such as our header becoming empty <header />.
We also saw some syntax errors like:
Uncaught exception 'ParseError' with message 'syntax error, unexpected ''({L(?!ToolIcon)[A-Z][a-z' (T_ENCAPSED_AND_WHITESPACE), expecting ']'' in /var/cache/.../template/header.c300a6673095bc267c3c22dbc8f8f196.rtpl.php:129

But after we tried to create a template for each session by adding sessionid to cache_dir:
$config = array(
			"base_url"    => Config::SITE_URL(),
			"tpl_dir"     => Config::TEMPLATE_PATH(),
			"cache_dir"   => Config::TEMPLATE_CACHE_PATH(),
			"cache_dir"   => $cache_path, /*Setting cache path to include sessionid */
			"debug"       => Config::SERVER() != SERVER_PRODUCTION,
			"auto_escape" => false
		);

we got rid of the errors, but now have a bunch of folders and template files for each session

**Comment by feulf** [comment]
Do not use a dynamic cache_dir. You want to use a static *cache_dir*, so that templates are compiled only once. Also, keep debug = false in production.

My guess is, the error you're getting is because one or more variables in your template, is using an invalid character, such as space, Unicode, or other. You can identify the variable that is causing the error and change that variable name.

**Comment by mejsin** [comment]
Thanks for input.
But seem dynamic cache_dir solved all our problems. 
I'll check if debug = false also helps.

**Comment by mejsin** [comment]
seems debug= false also helps :-)

**Comment by feulf** [comment]
The problem with using a dynamic cache is that you'll write a new template cache each time you have a new visit. This is slow and it will slowly fill the space in your server.

The point of using the cache is to compile the template only once so that the loading time is faster. 

I recommend debugging your template error and fixing it, get a static cache_dir, and then to keep debug=false in production. That will increase drastically the performance of your web application.

The best way to debugging the error is by identifying in local which variable is causing it, and try to change the variable name.

**Comment by mejsin** [comment]
ok thanks for the update!
we now run with static cache and debug=false, it works fine and faster now :-)
